import { 
  Produto, 
  Categoria, 
  ContaPagar, 
  ContaReceber, 
  NotaFiscal, 
  Venda, 
  OrdemServico, 
  Entrega,
  Tenant,
  User,
  CategoriaFinanceira,
  MovimentacaoEstoque,
  PlanoPreco
} from '@/types';

// Tenant Mock
export const mockTenant: Tenant = {
  id: 'tenant-001',
  nome: 'Empresa Demo LTDA',
  cnpj: '12.345.678/0001-90',
  email: 'contato@empresademo.com.br',
  telefone: '(11) 99999-9999',
  endereco: 'Rua das Flores, 123',
  cidade: 'São Paulo',
  estado: 'SP',
  plano: 'profissional',
  status: 'ativo',
  dataExpiracao: new Date('2025-12-31'),
  dataCriacao: new Date('2024-01-01'),
  configuracoes: {
    corPrimaria: '#3b82f6',
    corSecundaria: '#10b981',
    moeda: 'BRL',
    timezone: 'America/Sao_Paulo',
    notificacoesEmail: true,
    notificacoesSms: false
  }
};

// User Mock
export const mockUser: User = {
  id: 'user-001',
  email: 'admin@empresademo.com.br',
  nome: 'João Silva',
  role: 'admin',
  tenantId: 'tenant-001',
  ativo: true,
  dataCriacao: new Date('2024-01-01'),
  ultimoAcesso: new Date()
};

// Categorias Mock
export const mockCategorias: Categoria[] = [
  { id: 'cat-001', tenantId: 'tenant-001', nome: 'Eletrônicos', descricao: 'Produtos eletrônicos em geral', cor: '#3b82f6', ativo: true, ordem: 1 },
  { id: 'cat-002', tenantId: 'tenant-001', nome: 'Acessórios', descricao: 'Acessórios diversos', cor: '#10b981', ativo: true, ordem: 2 },
  { id: 'cat-003', tenantId: 'tenant-001', nome: 'Informática', descricao: 'Produtos de informática', cor: '#8b5cf6', ativo: true, ordem: 3 },
  { id: 'cat-004', tenantId: 'tenant-001', nome: 'Escritório', descricao: 'Materiais de escritório', cor: '#f59e0b', ativo: true, ordem: 4 },
  { id: 'cat-005', tenantId: 'tenant-001', nome: 'Utilidades', descricao: 'Produtos de utilidades', cor: '#ef4444', ativo: true, ordem: 5 },
];

// Produtos Mock
export const mockProdutos: Produto[] = [
  {
    id: 'prod-001',
    tenantId: 'tenant-001',
    codigo: 'PROD001',
    nome: 'Smartphone Samsung Galaxy S24',
    descricao: 'Smartphone Samsung Galaxy S24 256GB',
    categoriaId: 'cat-001',
    categoria: mockCategorias[0],
    ncm: '8517.12.31',
    cst: '000',
    cfop: '5102',
    unidade: 'UN',
    precoCusto: 2800,
    precoVenda: 3500,
    margemLucro: 25,
    estoqueAtual: 15,
    estoqueMinimo: 5,
    estoqueMaximo: 50,
    fornecedor: 'Samsung Brasil',
    ativo: true,
    dataCriacao: new Date('2024-01-15'),
    dataAtualizacao: new Date('2024-06-01')
  },
  {
    id: 'prod-002',
    tenantId: 'tenant-001',
    codigo: 'PROD002',
    nome: 'Notebook Dell Inspiron 15',
    descricao: 'Notebook Dell Inspiron 15 i5 8GB 256GB SSD',
    categoriaId: 'cat-003',
    categoria: mockCategorias[2],
    ncm: '8471.30.19',
    cst: '000',
    cfop: '5102',
    unidade: 'UN',
    precoCusto: 3200,
    precoVenda: 4200,
    margemLucro: 31.25,
    estoqueAtual: 8,
    estoqueMinimo: 3,
    estoqueMaximo: 20,
    fornecedor: 'Dell Brasil',
    ativo: true,
    dataCriacao: new Date('2024-01-20'),
    dataAtualizacao: new Date('2024-05-15')
  },
  {
    id: 'prod-003',
    tenantId: 'tenant-001',
    codigo: 'PROD003',
    nome: 'Mouse Logitech MX Master 3',
    descricao: 'Mouse sem fio Logitech MX Master 3',
    categoriaId: 'cat-002',
    categoria: mockCategorias[1],
    ncm: '8471.60.52',
    cst: '000',
    cfop: '5102',
    unidade: 'UN',
    precoCusto: 380,
    precoVenda: 520,
    margemLucro: 36.84,
    estoqueAtual: 25,
    estoqueMinimo: 10,
    estoqueMaximo: 100,
    fornecedor: 'Logitech',
    ativo: true,
    dataCriacao: new Date('2024-02-01'),
    dataAtualizacao: new Date('2024-06-10')
  },
  {
    id: 'prod-004',
    tenantId: 'tenant-001',
    codigo: 'PROD004',
    nome: 'Teclado Mecânico RGB',
    descricao: 'Teclado mecânico gaming RGB Blue Switch',
    categoriaId: 'cat-002',
    categoria: mockCategorias[1],
    ncm: '8473.30.11',
    cst: '000',
    cfop: '5102',
    unidade: 'UN',
    precoCusto: 180,
    precoVenda: 280,
    margemLucro: 55.56,
    estoqueAtual: 3,
    estoqueMinimo: 5,
    estoqueMaximo: 30,
    fornecedor: 'Importado',
    ativo: true,
    dataCriacao: new Date('2024-02-10'),
    dataAtualizacao: new Date('2024-05-20')
  },
  {
    id: 'prod-005',
    tenantId: 'tenant-001',
    codigo: 'PROD005',
    nome: 'Monitor LG 27" 4K',
    descricao: 'Monitor LG 27" 4K IPS 60Hz',
    categoriaId: 'cat-003',
    categoria: mockCategorias[2],
    ncm: '8528.52.29',
    cst: '000',
    cfop: '5102',
    unidade: 'UN',
    precoCusto: 1800,
    precoVenda: 2400,
    margemLucro: 33.33,
    estoqueAtual: 12,
    estoqueMinimo: 5,
    estoqueMaximo: 25,
    fornecedor: 'LG Brasil',
    ativo: true,
    dataCriacao: new Date('2024-02-15'),
    dataAtualizacao: new Date('2024-06-05')
  },
  {
    id: 'prod-006',
    tenantId: 'tenant-001',
    codigo: 'PROD006',
    nome: 'Fone Bluetooth JBL Tune',
    descricao: 'Fone de ouvido Bluetooth JBL Tune 500BT',
    categoriaId: 'cat-002',
    categoria: mockCategorias[1],
    ncm: '8518.30.00',
    cst: '000',
    cfop: '5102',
    unidade: 'UN',
    precoCusto: 180,
    precoVenda: 280,
    margemLucro: 55.56,
    estoqueAtual: 2,
    estoqueMinimo: 8,
    estoqueMaximo: 40,
    fornecedor: 'JBL',
    ativo: true,
    dataCriacao: new Date('2024-03-01'),
    dataAtualizacao: new Date('2024-06-08')
  },
  {
    id: 'prod-007',
    tenantId: 'tenant-001',
    codigo: 'PROD007',
    nome: 'Impressora HP LaserJet',
    descricao: 'Impressora HP LaserJet Pro M404dn',
    categoriaId: 'cat-004',
    categoria: mockCategorias[3],
    ncm: '8443.32.41',
    cst: '000',
    cfop: '5102',
    unidade: 'UN',
    precoCusto: 1500,
    precoVenda: 2100,
    margemLucro: 40,
    estoqueAtual: 6,
    estoqueMinimo: 3,
    estoqueMaximo: 15,
    fornecedor: 'HP Brasil',
    ativo: true,
    dataCriacao: new Date('2024-03-10'),
    dataAtualizacao: new Date('2024-05-25')
  },
  {
    id: 'prod-008',
    tenantId: 'tenant-001',
    codigo: 'PROD008',
    nome: 'Webcam Logitech C920',
    descricao: 'Webcam Logitech C920 HD Pro',
    categoriaId: 'cat-002',
    categoria: mockCategorias[1],
    ncm: '8525.80.19',
    cst: '000',
    cfop: '5102',
    unidade: 'UN',
    precoCusto: 350,
    precoVenda: 480,
    margemLucro: 37.14,
    estoqueAtual: 18,
    estoqueMinimo: 5,
    estoqueMaximo: 30,
    fornecedor: 'Logitech',
    ativo: true,
    dataCriacao: new Date('2024-03-15'),
    dataAtualizacao: new Date('2024-06-12')
  },
  {
    id: 'prod-009',
    tenantId: 'tenant-001',
    codigo: 'PROD009',
    nome: 'SSD Kingston 480GB',
    descricao: 'SSD Kingston A400 480GB SATA',
    categoriaId: 'cat-003',
    categoria: mockCategorias[2],
    ncm: '8471.70.10',
    cst: '000',
    cfop: '5102',
    unidade: 'UN',
    precoCusto: 220,
    precoVenda: 320,
    margemLucro: 45.45,
    estoqueAtual: 45,
    estoqueMinimo: 15,
    estoqueMaximo: 100,
    fornecedor: 'Kingston',
    ativo: true,
    dataCriacao: new Date('2024-03-20'),
    dataAtualizacao: new Date('2024-06-15')
  },
  {
    id: 'prod-010',
    tenantId: 'tenant-001',
    codigo: 'PROD010',
    nome: 'Memória RAM 16GB DDR4',
    descricao: 'Memória RAM 16GB DDR4 3200MHz',
    categoriaId: 'cat-003',
    categoria: mockCategorias[2],
    ncm: '8542.32.31',
    cst: '000',
    cfop: '5102',
    unidade: 'UN',
    precoCusto: 280,
    precoVenda: 380,
    margemLucro: 35.71,
    estoqueAtual: 1,
    estoqueMinimo: 10,
    estoqueMaximo: 50,
    fornecedor: 'Kingston',
    ativo: true,
    dataCriacao: new Date('2024-04-01'),
    dataAtualizacao: new Date('2024-06-18')
  },
];

// Categorias Financeiras Mock
export const mockCategoriasFinanceiras: CategoriaFinanceira[] = [
  { id: 'cf-001', tenantId: 'tenant-001', nome: 'Vendas', tipo: 'receita', cor: '#10b981', ativo: true },
  { id: 'cf-002', tenantId: 'tenant-001', nome: 'Serviços', tipo: 'receita', cor: '#3b82f6', ativo: true },
  { id: 'cf-003', tenantId: 'tenant-001', nome: 'Fornecedores', tipo: 'despesa', cor: '#ef4444', ativo: true },
  { id: 'cf-004', tenantId: 'tenant-001', nome: 'Salários', tipo: 'despesa', cor: '#f59e0b', ativo: true },
  { id: 'cf-005', tenantId: 'tenant-001', nome: 'Aluguel', tipo: 'despesa', cor: '#8b5cf6', ativo: true },
  { id: 'cf-006', tenantId: 'tenant-001', nome: 'Energia', tipo: 'despesa', cor: '#06b6d4', ativo: true },
  { id: 'cf-007', tenantId: 'tenant-001', nome: 'Internet/Telefone', tipo: 'despesa', cor: '#ec4899', ativo: true },
  { id: 'cf-008', tenantId: 'tenant-001', nome: 'Impostos', tipo: 'despesa', cor: '#64748b', ativo: true },
];

// Contas a Pagar Mock
export const mockContasPagar: ContaPagar[] = [
  {
    id: 'cp-001',
    tenantId: 'tenant-001',
    descricao: 'Fornecedor Samsung - Smartphones',
    valor: 28000,
    dataVencimento: new Date('2024-06-25'),
    status: 'pendente',
    categoriaId: 'cf-003',
    categoria: mockCategoriasFinanceiras[2],
    fornecedor: 'Samsung Brasil',
    documento: 'NF 12345',
    recorrente: false,
    dataCriacao: new Date('2024-06-01')
  },
  {
    id: 'cp-002',
    tenantId: 'tenant-001',
    descricao: 'Aluguel do mês',
    valor: 3500,
    dataVencimento: new Date('2024-06-10'),
    status: 'pago',
    dataPagamento: new Date('2024-06-08'),
    categoriaId: 'cf-005',
    categoria: mockCategoriasFinanceiras[4],
    fornecedor: 'Imobiliária ABC',
    documento: 'REC 001',
    recorrente: true,
    frequencia: 'mensal',
    dataCriacao: new Date('2024-06-01')
  },
  {
    id: 'cp-003',
    tenantId: 'tenant-001',
    descricao: 'Conta de Energia',
    valor: 850,
    dataVencimento: new Date('2024-06-15'),
    status: 'pago',
    dataPagamento: new Date('2024-06-14'),
    categoriaId: 'cf-006',
    categoria: mockCategoriasFinanceiras[5],
    fornecedor: 'Enel Energia',
    documento: 'FAT 78901',
    recorrente: true,
    frequencia: 'mensal',
    dataCriacao: new Date('2024-06-01')
  },
  {
    id: 'cp-004',
    tenantId: 'tenant-001',
    descricao: 'Folha de Pagamento',
    valor: 25000,
    dataVencimento: new Date('2024-06-05'),
    status: 'pago',
    dataPagamento: new Date('2024-06-05'),
    categoriaId: 'cf-004',
    categoria: mockCategoriasFinanceiras[3],
    fornecedor: 'Funcionários',
    documento: 'FP 06/2024',
    recorrente: true,
    frequencia: 'mensal',
    dataCriacao: new Date('2024-06-01')
  },
  {
    id: 'cp-005',
    tenantId: 'tenant-001',
    descricao: 'Internet Fibra',
    valor: 299,
    dataVencimento: new Date('2024-06-20'),
    status: 'vencido',
    categoriaId: 'cf-007',
    categoria: mockCategoriasFinanceiras[6],
    fornecedor: 'Vivo Fibra',
    documento: 'FAT 45678',
    recorrente: true,
    frequencia: 'mensal',
    dataCriacao: new Date('2024-06-01')
  },
  {
    id: 'cp-006',
    tenantId: 'tenant-001',
    descricao: 'Fornecedor Dell - Notebooks',
    valor: 19200,
    dataVencimento: new Date('2024-06-28'),
    status: 'pendente',
    categoriaId: 'cf-003',
    categoria: mockCategoriasFinanceiras[2],
    fornecedor: 'Dell Brasil',
    documento: 'NF 67890',
    recorrente: false,
    dataCriacao: new Date('2024-06-10')
  },
  {
    id: 'cp-007',
    tenantId: 'tenant-001',
    descricao: 'ICMS - Maio/2024',
    valor: 4500,
    dataVencimento: new Date('2024-06-20'),
    status: 'vencido',
    categoriaId: 'cf-008',
    categoria: mockCategoriasFinanceiras[7],
    fornecedor: 'SEFAZ SP',
    documento: 'GARE 05/2024',
    recorrente: true,
    frequencia: 'mensal',
    dataCriacao: new Date('2024-06-01')
  },
];

// Contas a Receber Mock
export const mockContasReceber: ContaReceber[] = [
  {
    id: 'cr-001',
    tenantId: 'tenant-001',
    descricao: 'Venda para Cliente ABC',
    valor: 8500,
    dataVencimento: new Date('2024-06-15'),
    status: 'pago',
    dataRecebimento: new Date('2024-06-14'),
    categoriaId: 'cf-001',
    categoria: mockCategoriasFinanceiras[0],
    cliente: 'ABC Comércio LTDA',
    documento: 'VENDA 001234',
    recorrente: false,
    dataCriacao: new Date('2024-06-01')
  },
  {
    id: 'cr-002',
    tenantId: 'tenant-001',
    descricao: 'Prestação de Serviços - XYZ',
    valor: 3200,
    dataVencimento: new Date('2024-06-25'),
    status: 'pendente',
    categoriaId: 'cf-002',
    categoria: mockCategoriasFinanceiras[1],
    cliente: 'XYZ Indústria SA',
    documento: 'OS 00567',
    recorrente: false,
    dataCriacao: new Date('2024-06-05')
  },
  {
    id: 'cr-003',
    tenantId: 'tenant-001',
    descricao: 'Venda parcelada - Cliente DEF',
    valor: 2400,
    dataVencimento: new Date('2024-06-10'),
    status: 'vencido',
    categoriaId: 'cf-001',
    categoria: mockCategoriasFinanceiras[0],
    cliente: 'DEF Serviços ME',
    documento: 'VENDA 001235',
    recorrente: false,
    dataCriacao: new Date('2024-05-10')
  },
  {
    id: 'cr-004',
    tenantId: 'tenant-001',
    descricao: 'Manutenção mensal - Cliente GHI',
    valor: 1500,
    dataVencimento: new Date('2024-06-30'),
    status: 'pendente',
    categoriaId: 'cf-002',
    categoria: mockCategoriasFinanceiras[1],
    cliente: 'GHI Tecnologia',
    documento: 'CONTRATO 001',
    recorrente: true,
    frequencia: 'mensal',
    dataCriacao: new Date('2024-06-01')
  },
  {
    id: 'cr-005',
    tenantId: 'tenant-001',
    descricao: 'Venda de equipamentos',
    valor: 12600,
    dataVencimento: new Date('2024-06-28'),
    status: 'pendente',
    categoriaId: 'cf-001',
    categoria: mockCategoriasFinanceiras[0],
    cliente: 'JKL Corp',
    documento: 'VENDA 001240',
    recorrente: false,
    dataCriacao: new Date('2024-06-12')
  },
  {
    id: 'cr-006',
    tenantId: 'tenant-001',
    descricao: 'Consultoria técnica',
    valor: 2800,
    dataVencimento: new Date('2024-06-05'),
    status: 'pago',
    dataRecebimento: new Date('2024-06-04'),
    categoriaId: 'cf-002',
    categoria: mockCategoriasFinanceiras[1],
    cliente: 'MNO Solutions',
    documento: 'CONSULT 0045',
    recorrente: false,
    dataCriacao: new Date('2024-05-20')
  },
];

// Notas Fiscais Mock
export const mockNotasFiscais: NotaFiscal[] = [
  {
    id: 'nf-001',
    tenantId: 'tenant-001',
    numero: 12345,
    serie: '1',
    modelo: '55',
    chave: '35240612345678000190550010000123451123456789',
    protocolo: '135240123456789',
    emitente: {
      razaoSocial: 'Empresa Demo LTDA',
      nomeFantasia: 'Demo Tech',
      cnpj: '12.345.678/0001-90',
      inscricaoEstadual: '123.456.789.123',
      endereco: {
        logradouro: 'Rua das Flores',
        numero: '123',
        bairro: 'Centro',
        cidade: 'São Paulo',
        estado: 'SP',
        cep: '01234-567'
      }
    },
    destinatario: {
      nome: 'ABC Comércio LTDA',
      documento: '98.765.432/0001-21',
      tipoDocumento: 'cnpj',
      endereco: {
        logradouro: 'Av. Principal',
        numero: '1000',
        bairro: 'Vila Nova',
        cidade: 'São Paulo',
        estado: 'SP',
        cep: '04567-000'
      },
      email: 'contato@abc.com.br'
    },
    produtos: [
      {
        item: 1,
        codigo: 'PROD001',
        descricao: 'Smartphone Samsung Galaxy S24',
        ncm: '8517.12.31',
        cst: '000',
        cfop: '5102',
        unidade: 'UN',
        quantidade: 2,
        valorUnitario: 3500,
        valorTotal: 7000,
        valorDesconto: 0,
        valorIpi: 0,
        valorIcms: 1120,
        valorPis: 0,
        valorCofins: 0
      }
    ],
    valorProdutos: 7000,
    valorServicos: 0,
    valorFrete: 0,
    valorSeguro: 0,
    valorDesconto: 0,
    valorTotal: 7000,
    valorIpi: 0,
    valorIcms: 1120,
    valorPis: 0,
    valorCofins: 0,
    dataEmissao: new Date('2024-06-15'),
    status: 'autorizada',
    naturezaOperacao: 'Venda de mercadorias',
    observacoes: 'Venda para consumidor final'
  },
  {
    id: 'nf-002',
    tenantId: 'tenant-001',
    numero: 12346,
    serie: '1',
    modelo: '65',
    chave: '35240612345678000190550010000123462123456789',
    protocolo: '135240123456790',
    emitente: {
      razaoSocial: 'Empresa Demo LTDA',
      nomeFantasia: 'Demo Tech',
      cnpj: '12.345.678/0001-90',
      inscricaoEstadual: '123.456.789.123',
      endereco: {
        logradouro: 'Rua das Flores',
        numero: '123',
        bairro: 'Centro',
        cidade: 'São Paulo',
        estado: 'SP',
        cep: '01234-567'
      }
    },
    destinatario: {
      nome: 'Consumidor Final',
      documento: '123.456.789-00',
      tipoDocumento: 'cpf',
      endereco: {
        logradouro: 'Rua A',
        numero: '100',
        bairro: 'Centro',
        cidade: 'São Paulo',
        estado: 'SP',
        cep: '01000-000'
      }
    },
    produtos: [
      {
        item: 1,
        codigo: 'PROD003',
        descricao: 'Mouse Logitech MX Master 3',
        ncm: '8471.60.52',
        cst: '000',
        cfop: '5102',
        unidade: 'UN',
        quantidade: 1,
        valorUnitario: 520,
        valorTotal: 520,
        valorDesconto: 0,
        valorIpi: 0,
        valorIcms: 83.2,
        valorPis: 0,
        valorCofins: 0
      }
    ],
    valorProdutos: 520,
    valorServicos: 0,
    valorFrete: 0,
    valorSeguro: 0,
    valorDesconto: 0,
    valorTotal: 520,
    valorIpi: 0,
    valorIcms: 83.2,
    valorPis: 0,
    valorCofins: 0,
    dataEmissao: new Date('2024-06-18'),
    status: 'autorizada',
    naturezaOperacao: 'Venda ao consumidor final'
  },
  {
    id: 'nf-003',
    tenantId: 'tenant-001',
    numero: 12347,
    serie: '1',
    modelo: '55',
    chave: '35240612345678000190550010000123473123456789',
    emitente: {
      razaoSocial: 'Empresa Demo LTDA',
      nomeFantasia: 'Demo Tech',
      cnpj: '12.345.678/0001-90',
      inscricaoEstadual: '123.456.789.123',
      endereco: {
        logradouro: 'Rua das Flores',
        numero: '123',
        bairro: 'Centro',
        cidade: 'São Paulo',
        estado: 'SP',
        cep: '01234-567'
      }
    },
    destinatario: {
      nome: 'JKL Corp',
      documento: '45.678.901/0001-23',
      tipoDocumento: 'cnpj',
      endereco: {
        logradouro: 'Av. Industrial',
        numero: '500',
        bairro: 'Industrial',
        cidade: 'Guarulhos',
        estado: 'SP',
        cep: '07000-000'
      }
    },
    produtos: [
      {
        item: 1,
        codigo: 'PROD002',
        descricao: 'Notebook Dell Inspiron 15',
        ncm: '8471.30.19',
        cst: '000',
        cfop: '5102',
        unidade: 'UN',
        quantidade: 3,
        valorUnitario: 4200,
        valorTotal: 12600,
        valorDesconto: 0,
        valorIpi: 0,
        valorIcms: 2016,
        valorPis: 0,
        valorCofins: 0
      }
    ],
    valorProdutos: 12600,
    valorServicos: 0,
    valorFrete: 0,
    valorSeguro: 0,
    valorDesconto: 0,
    valorTotal: 12600,
    valorIpi: 0,
    valorIcms: 2016,
    valorPis: 0,
    valorCofins: 0,
    dataEmissao: new Date('2024-06-20'),
    status: 'em_digitacao',
    naturezaOperacao: 'Venda de mercadorias'
  },
];

// Vendas Mock
export const mockVendas: Venda[] = [
  {
    id: 'venda-001',
    tenantId: 'tenant-001',
    numero: 1,
    cliente: 'ABC Comércio LTDA',
    clienteId: 'cli-001',
    itens: [
      {
        id: 'item-001',
        produtoId: 'prod-001',
        codigo: 'PROD001',
        descricao: 'Smartphone Samsung Galaxy S24',
        quantidade: 2,
        valorUnitario: 3500,
        desconto: 0,
        acrescimo: 0,
        valorTotal: 7000
      }
    ],
    subtotal: 7000,
    desconto: 0,
    acrescimo: 0,
    total: 7000,
    formaPagamento: 'boleto',
    valorPago: 7000,
    troco: 0,
    status: 'finalizada',
    vendedor: 'João Silva',
    dataCriacao: new Date('2024-06-15T10:30:00'),
    dataFinalizacao: new Date('2024-06-15T10:35:00')
  },
  {
    id: 'venda-002',
    tenantId: 'tenant-001',
    numero: 2,
    itens: [
      {
        id: 'item-002',
        produtoId: 'prod-003',
        codigo: 'PROD003',
        descricao: 'Mouse Logitech MX Master 3',
        quantidade: 1,
        valorUnitario: 520,
        desconto: 0,
        acrescimo: 0,
        valorTotal: 520
      }
    ],
    subtotal: 520,
    desconto: 0,
    acrescimo: 0,
    total: 520,
    formaPagamento: 'cartao_credito',
    valorPago: 520,
    troco: 0,
    status: 'finalizada',
    vendedor: 'João Silva',
    dataCriacao: new Date('2024-06-18T14:20:00'),
    dataFinalizacao: new Date('2024-06-18T14:25:00')
  },
  {
    id: 'venda-003',
    tenantId: 'tenant-001',
    numero: 3,
    cliente: 'JKL Corp',
    clienteId: 'cli-002',
    itens: [
      {
        id: 'item-003',
        produtoId: 'prod-002',
        codigo: 'PROD002',
        descricao: 'Notebook Dell Inspiron 15',
        quantidade: 3,
        valorUnitario: 4200,
        desconto: 0,
        acrescimo: 0,
        valorTotal: 12600
      }
    ],
    subtotal: 12600,
    desconto: 600,
    acrescimo: 0,
    total: 12000,
    formaPagamento: 'boleto',
    valorPago: 12000,
    troco: 0,
    status: 'finalizada',
    vendedor: 'Maria Santos',
    dataCriacao: new Date('2024-06-20T09:15:00'),
    dataFinalizacao: new Date('2024-06-20T09:30:00')
  },
];

// Ordens de Serviço Mock
export const mockOrdensServico: OrdemServico[] = [
  {
    id: 'os-001',
    tenantId: 'tenant-001',
    numero: 1,
    cliente: 'Maria Oliveira',
    telefone: '(11) 98765-4321',
    email: 'maria@email.com',
    equipamento: 'Notebook Dell Inspiron',
    numeroSerie: 'DELL123456',
    defeitoRelatado: 'Notebook não liga, fonte funcionando',
    defeitoConstatado: 'Placa-mãe com componente queimado',
    solucao: 'Substituição do capacitor C45 na placa-mãe',
    produtos: [
      { id: 'pos-001', produtoId: 'prod-009', descricao: 'SSD Kingston 480GB', quantidade: 1, valorUnitario: 320, valorTotal: 320 }
    ],
    servicos: [
      { id: 'sos-001', descricao: 'Troca de capacitor', quantidade: 1, valorUnitario: 150, valorTotal: 150 },
      { id: 'sos-002', descricao: 'Instalação do SSD', quantidade: 1, valorUnitario: 50, valorTotal: 50 }
    ],
    valorProdutos: 320,
    valorServicos: 200,
    valorTotal: 520,
    desconto: 0,
    status: 'em_andamento',
    prioridade: 'alta',
    tecnico: 'Carlos Técnico',
    dataAbertura: new Date('2024-06-15'),
    dataPrevisao: new Date('2024-06-22'),
    observacoes: 'Cliente com urgência, equipamento usado para trabalho'
  },
  {
    id: 'os-002',
    tenantId: 'tenant-001',
    numero: 2,
    cliente: 'João Pedro',
    telefone: '(11) 99876-5432',
    email: 'joao.pedro@email.com',
    equipamento: 'Smartphone Samsung Galaxy S20',
    numeroSerie: 'SAM789012',
    defeitoRelatado: 'Tela trincada após queda',
    defeitoConstatado: 'LCD quebrado, touch funcionando parcialmente',
    solucao: 'Substituição do display completo',
    produtos: [],
    servicos: [
      { id: 'sos-003', descricao: 'Troca de display Galaxy S20', quantidade: 1, valorUnitario: 450, valorTotal: 450 }
    ],
    valorProdutos: 0,
    valorServicos: 450,
    valorTotal: 450,
    desconto: 0,
    status: 'aguardando_pecas',
    prioridade: 'normal',
    tecnico: 'Carlos Técnico',
    dataAbertura: new Date('2024-06-18'),
    dataPrevisao: new Date('2024-06-28'),
    observacoes: 'Aguardando chegada do display novo'
  },
  {
    id: 'os-003',
    tenantId: 'tenant-001',
    numero: 3,
    cliente: 'Empresa ABC LTDA',
    telefone: '(11) 3456-7890',
    email: 'suporte@abc.com.br',
    equipamento: 'Impressora HP LaserJet Pro',
    numeroSerie: 'HP345678',
    defeitoRelatado: 'Impressão com manchas escuras',
    defeitoConstatado: 'Toner vazio e cilindro desgastado',
    solucao: 'Substituição do toner e limpeza do cilindro',
    produtos: [],
    servicos: [
      { id: 'sos-004', descricao: 'Manutenção preventiva', quantidade: 1, valorUnitario: 120, valorTotal: 120 }
    ],
    valorProdutos: 0,
    valorServicos: 120,
    valorTotal: 120,
    desconto: 0,
    status: 'concluida',
    prioridade: 'normal',
    tecnico: 'Carlos Técnico',
    dataAbertura: new Date('2024-06-10'),
    dataPrevisao: new Date('2024-06-12'),
    dataConclusao: new Date('2024-06-11'),
    observacoes: 'Manutenção realizada com sucesso'
  },
  {
    id: 'os-004',
    tenantId: 'tenant-001',
    numero: 4,
    cliente: 'Ana Silva',
    telefone: '(11) 91234-5678',
    email: 'ana.silva@email.com',
    equipamento: 'Desktop PC Gamer',
    defeitoRelatado: 'PC reiniciando sozinho durante jogos',
    produtos: [],
    servicos: [],
    valorProdutos: 0,
    valorServicos: 0,
    valorTotal: 0,
    desconto: 0,
    status: 'aberta',
    prioridade: 'baixa',
    dataAbertura: new Date('2024-06-21'),
    observacoes: 'Cliente relatou problema após upgrade de placa de vídeo'
  },
];

// Entregas Mock
export const mockEntregas: Entrega[] = [
  {
    id: 'ent-001',
    tenantId: 'tenant-001',
    vendaId: 'venda-001',
    cliente: 'ABC Comércio LTDA',
    endereco: {
      logradouro: 'Av. Principal',
      numero: '1000',
      bairro: 'Vila Nova',
      cidade: 'São Paulo',
      estado: 'SP',
      cep: '04567-000'
    },
    telefone: '(11) 3456-7890',
    observacoes: 'Entregar no recebimento',
    valorFrete: 50,
    status: 'entregue',
    entregador: 'Paulo Entregador',
    dataPrevista: new Date('2024-06-16'),
    dataEntrega: new Date('2024-06-16'),
    horarioSaida: new Date('2024-06-16T08:00:00'),
    horarioEntrega: new Date('2024-06-16T10:30:00')
  },
  {
    id: 'ent-002',
    tenantId: 'tenant-001',
    vendaId: 'venda-003',
    cliente: 'JKL Corp',
    endereco: {
      logradouro: 'Av. Industrial',
      numero: '500',
      bairro: 'Industrial',
      cidade: 'Guarulhos',
      estado: 'SP',
      cep: '07000-000'
    },
    telefone: '(11) 2345-6789',
    valorFrete: 0,
    status: 'pendente',
    dataPrevista: new Date('2024-06-22')
  },
];

// Movimentações de Estoque Mock
export const mockMovimentacoes: MovimentacaoEstoque[] = [
  {
    id: 'mov-001',
    tenantId: 'tenant-001',
    produtoId: 'prod-001',
    tipo: 'entrada',
    quantidade: 10,
    estoqueAnterior: 5,
    estoqueAtual: 15,
    motivo: 'Compra de fornecedor',
    documento: 'NF 54321',
    usuarioId: 'user-001',
    usuario: 'João Silva',
    dataCriacao: new Date('2024-06-01')
  },
  {
    id: 'mov-002',
    tenantId: 'tenant-001',
    produtoId: 'prod-001',
    tipo: 'saida',
    quantidade: 2,
    estoqueAnterior: 17,
    estoqueAtual: 15,
    motivo: 'Venda',
    documento: 'VENDA 001234',
    usuarioId: 'user-001',
    usuario: 'João Silva',
    dataCriacao: new Date('2024-06-15')
  },
  {
    id: 'mov-003',
    tenantId: 'tenant-001',
    produtoId: 'prod-010',
    tipo: 'saida',
    quantidade: 5,
    estoqueAnterior: 6,
    estoqueAtual: 1,
    motivo: 'Venda',
    documento: 'VENDA 001238',
    usuarioId: 'user-001',
    usuario: 'João Silva',
    dataCriacao: new Date('2024-06-19')
  },
];

// Planos Mock
export const mockPlanos: PlanoPreco[] = [
  {
    id: 'plano-001',
    nome: 'Básico',
    descricao: 'Ideal para pequenos negócios começando com gestão digital',
    precoMensal: 79.90,
    precoAnual: 799.90,
    recursos: [
      { nome: 'Até 2 usuários', incluido: true, limite: 2 },
      { nome: 'Até 100 produtos', incluido: true, limite: 100 },
      { nome: 'Controle de estoque', incluido: true },
      { nome: 'Contas a pagar/receber', incluido: true },
      { nome: 'PDV básico', incluido: true },
      { nome: 'Relatórios básicos', incluido: true },
      { nome: 'Suporte por email', incluido: true },
      { nome: 'Emissão de NF-e', incluido: false },
      { nome: 'Multi-filial', incluido: false },
      { nome: 'API de integração', incluido: false },
    ],
    limiteUsuarios: 2,
    limiteProdutos: 100,
    limiteVendas: 500,
    suporte: 'email',
    ativo: true,
    destaque: false
  },
  {
    id: 'plano-002',
    nome: 'Profissional',
    descricao: 'Perfeito para empresas em crescimento com necessidades avançadas',
    precoMensal: 159.90,
    precoAnual: 1599.90,
    recursos: [
      { nome: 'Até 5 usuários', incluido: true, limite: 5 },
      { nome: 'Até 500 produtos', incluido: true, limite: 500 },
      { nome: 'Controle de estoque avançado', incluido: true },
      { nome: 'Contas a pagar/receber', incluido: true },
      { nome: 'PDV completo', incluido: true },
      { nome: 'Relatórios avançados', incluido: true },
      { nome: 'Emissão de NF-e/NFC-e', incluido: true },
      { nome: 'Ordens de serviço', incluido: true },
      { nome: 'Suporte por chat', incluido: true },
      { nome: 'Multi-filial', incluido: false },
    ],
    limiteUsuarios: 5,
    limiteProdutos: 500,
    limiteVendas: 2000,
    suporte: 'chat',
    ativo: true,
    destaque: true
  },
  {
    id: 'plano-003',
    nome: 'Enterprise',
    descricao: 'Solução completa para grandes operações',
    precoMensal: 349.90,
    precoAnual: 3499.90,
    recursos: [
      { nome: 'Usuários ilimitados', incluido: true },
      { nome: 'Produtos ilimitados', incluido: true },
      { nome: 'Todas as funcionalidades', incluido: true },
      { nome: 'Multi-filial', incluido: true },
      { nome: 'API de integração', incluido: true },
      { nome: 'Personalização avançada', incluido: true },
      { nome: 'Treinamento personalizado', incluido: true },
      { nome: 'Suporte prioritário 24/7', incluido: true },
      { nome: 'Gerente de conta dedicado', incluido: true },
      { nome: 'SLA garantido', incluido: true },
    ],
    limiteUsuarios: 999,
    limiteProdutos: 99999,
    limiteVendas: 99999,
    suporte: 'prioritario',
    ativo: true,
    destaque: false
  },
];

// Tenants para Admin
export const mockTenantsAdmin: Tenant[] = [
  mockTenant,
  {
    id: 'tenant-002',
    nome: 'Tech Solutions SA',
    cnpj: '98.765.432/0001-10',
    email: 'contato@techsolutions.com.br',
    telefone: '(21) 99876-5432',
    endereco: 'Av. Rio Branco, 1000',
    cidade: 'Rio de Janeiro',
    estado: 'RJ',
    plano: 'enterprise',
    status: 'ativo',
    dataExpiracao: new Date('2025-06-30'),
    dataCriacao: new Date('2024-02-15'),
    configuracoes: {
      corPrimaria: '#8b5cf6',
      corSecundaria: '#f59e0b',
      moeda: 'BRL',
      timezone: 'America/Sao_Paulo',
      notificacoesEmail: true,
      notificacoesSms: true
    }
  },
  {
    id: 'tenant-003',
    nome: 'Mercearia do João',
    cnpj: '45.678.901/0001-23',
    email: 'joao@mercearia.com.br',
    telefone: '(31) 98765-1234',
    endereco: 'Rua da Praça, 50',
    cidade: 'Belo Horizonte',
    estado: 'MG',
    plano: 'basico',
    status: 'suspenso',
    dataExpiracao: new Date('2024-06-01'),
    dataCriacao: new Date('2024-01-10'),
    configuracoes: {
      corPrimaria: '#10b981',
      corSecundaria: '#3b82f6',
      moeda: 'BRL',
      timezone: 'America/Sao_Paulo',
      notificacoesEmail: false,
      notificacoesSms: false
    }
  },
  {
    id: 'tenant-004',
    nome: 'Auto Peças Silva',
    cnpj: '67.890.123/0001-45',
    email: 'vendas@autopecassilva.com.br',
    telefone: '(41) 99999-8888',
    endereco: 'Av. Brasil, 2000',
    cidade: 'Curitiba',
    estado: 'PR',
    plano: 'profissional',
    status: 'ativo',
    dataExpiracao: new Date('2024-12-31'),
    dataCriacao: new Date('2024-03-01'),
    configuracoes: {
      corPrimaria: '#ef4444',
      corSecundaria: '#64748b',
      moeda: 'BRL',
      timezone: 'America/Sao_Paulo',
      notificacoesEmail: true,
      notificacoesSms: false
    }
  },
  {
    id: 'tenant-005',
    nome: 'Loja de Roupas Fashion',
    cnpj: '23.456.789/0001-67',
    email: 'contato@fashionstore.com.br',
    telefone: '(51) 99888-7777',
    endereco: 'Shopping Center, Loja 100',
    cidade: 'Porto Alegre',
    estado: 'RS',
    plano: 'basico',
    status: 'expirado',
    dataExpiracao: new Date('2024-05-15'),
    dataCriacao: new Date('2023-11-15'),
    configuracoes: {
      corPrimaria: '#ec4899',
      corSecundaria: '#06b6d4',
      moeda: 'BRL',
      timezone: 'America/Sao_Paulo',
      notificacoesEmail: true,
      notificacoesSms: true
    }
  },
];

// Dashboard Chart Data
export const mockVendasChartData = [
  { mes: 'Jan', vendas: 45, receita: 45000, despesas: 32000, lucro: 13000 },
  { mes: 'Fev', vendas: 52, receita: 52000, despesas: 35000, lucro: 17000 },
  { mes: 'Mar', vendas: 48, receita: 48000, despesas: 30000, lucro: 18000 },
  { mes: 'Abr', vendas: 61, receita: 61000, despesas: 38000, lucro: 23000 },
  { mes: 'Mai', vendas: 55, receita: 55000, despesas: 33000, lucro: 22000 },
  { mes: 'Jun', vendas: 67, receita: 67000, despesas: 40000, lucro: 27000 },
];

export const mockFluxoCaixaData = [
  { data: '01/06', entradas: 8500, saidas: 25000, saldo: -16500 },
  { data: '05/06', entradas: 2800, saidas: 0, saldo: -13700 },
  { data: '10/06', entradas: 0, saidas: 3500, saldo: -17200 },
  { data: '14/06', entradas: 0, saidas: 850, saldo: -18050 },
  { data: '15/06', entradas: 8500, saidas: 0, saldo: -9550 },
  { data: '20/06', entradas: 0, saidas: 4799, saldo: -14349 },
  { data: '25/06', entradas: 3200, saidas: 0, saldo: -11149 },
  { data: '28/06', entradas: 12600, saidas: 47200, saldo: -45749 },
];

export const mockVendasPorCategoria = [
  { name: 'Eletrônicos', value: 45000, color: '#3b82f6' },
  { name: 'Informática', value: 32000, color: '#8b5cf6' },
  { name: 'Acessórios', value: 18000, color: '#10b981' },
  { name: 'Escritório', value: 8000, color: '#f59e0b' },
  { name: 'Utilidades', value: 5000, color: '#ef4444' },
];
